apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-sql-db
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-sql
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-sql-db.git
      sourceType: git
    description: {}
  content:
    subBlueprints:
      - name: backup
        location: modules/backup
      - name: mssql
        location: modules/mssql
      - name: mysql
        location: modules/mysql
      - name: postgresql
        location: modules/postgresql
      - name: private_service_access
        location: modules/private_service_access
      - name: restore
        location: modules/restore
      - name: safer_mysql
        location: modules/safer_mysql
    examples:
      - name: mssql-failover-replica
        location: examples/mssql-failover-replica
      - name: mssql-public
        location: examples/mssql-public
      - name: mysql-backup-create-service-account
        location: examples/mysql-backup-create-service-account
      - name: mysql-ha
        location: examples/mysql-ha
      - name: mysql-private
        location: examples/mysql-private
      - name: mysql-psc
        location: examples/mysql-psc
      - name: mysql-public
        location: examples/mysql-public
      - name: postgresql-backup-provided-service-account
        location: examples/postgresql-backup-provided-service-account
      - name: postgresql-ha
        location: examples/postgresql-ha
      - name: postgresql-psc
        location: examples/postgresql-psc
      - name: postgresql-public
        location: examples/postgresql-public
      - name: postgresql-public-iam
        location: examples/postgresql-public-iam
      - name: postgresql-with-cross-region-failover
        location: examples/postgresql-with-cross-region-failover
      - name: private_service_access
        location: examples/private_service_access
  interfaces: {}
  requirements:
    roles:
      - level: Project
        roles:
          - roles/resourcemanager.projectIamAdmin
          - roles/serviceusage.serviceUsageAdmin
          - roles/cloudsql.admin
          - roles/iam.serviceAccountAdmin
          - roles/iam.serviceAccountUser
    services:
      - cloudresourcemanager.googleapis.com
      - iam.googleapis.com
      - serviceusage.googleapis.com
      - sqladmin.googleapis.com
