# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-sql-db
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-sql for MSSQL Server
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-sql-db.git
      sourceType: git
      dir: /modules/mssql
    version: 22.1.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: mssql-failover-replica
        location: examples/mssql-failover-replica
      - name: mssql-public
        location: examples/mssql-public
      - name: mysql-backup-create-service-account
        location: examples/mysql-backup-create-service-account
      - name: mysql-ha
        location: examples/mysql-ha
      - name: mysql-private
        location: examples/mysql-private
      - name: mysql-psc
        location: examples/mysql-psc
      - name: mysql-public
        location: examples/mysql-public
      - name: postgresql-backup-provided-service-account
        location: examples/postgresql-backup-provided-service-account
      - name: postgresql-ha
        location: examples/postgresql-ha
      - name: postgresql-psc
        location: examples/postgresql-psc
      - name: postgresql-public
        location: examples/postgresql-public
      - name: postgresql-public-iam
        location: examples/postgresql-public-iam
      - name: postgresql-with-cross-region-failover
        location: examples/postgresql-with-cross-region-failover
      - name: private_service_access
        location: examples/private_service_access
  interfaces:
    variables:
      - name: activation_policy
        description: The activation policy for the Cloud SQL instance. Can be either `ALWAYS`, `NEVER` or `ON_DEMAND`.
        varType: string
        defaultValue: ALWAYS
      - name: active_directory_config
        description: Active domain that the SQL instance will join.
        varType: map(string)
        defaultValue: {}
      - name: additional_databases
        description: A list of databases to be created in your cluster
        varType: |-
          list(object({
              name      = string
              charset   = string
              collation = string
            }))
        defaultValue: []
      - name: additional_users
        description: A list of users to be created in your cluster. A random password would be set for the user if the `random_password` variable is set.
        varType: |-
          list(object({
              name            = string
              password        = string
              random_password = bool
            }))
        defaultValue: []
      - name: availability_type
        description: The availability type for the Cloud SQL instance.This is only used to set up high availability for the MSSQL instance. Can be either `ZONAL` or `REGIONAL`.
        varType: string
        defaultValue: ZONAL
      - name: backup_configuration
        description: The database backup configuration.
        varType: |-
          object({
              binary_log_enabled             = bool
              enabled                        = bool
              point_in_time_recovery_enabled = bool
              start_time                     = string
              transaction_log_retention_days = string
              retained_backups               = number
              retention_unit                 = string
            })
        defaultValue:
          binary_log_enabled: null
          enabled: false
          point_in_time_recovery_enabled: null
          retained_backups: null
          retention_unit: null
          start_time: null
          transaction_log_retention_days: null
      - name: connector_enforcement
        description: Enforce that clients use the connector library
        varType: bool
        defaultValue: false
      - name: create_timeout
        description: The optional timeout that is applied to limit long database creates.
        varType: string
        defaultValue: 30m
      - name: database_flags
        description: The database flags for the Cloud SQL. See [more details](https://cloud.google.com/sql/docs/sqlserver/flags)
        varType: |-
          list(object({
              name  = string
              value = string
            }))
        defaultValue: []
      - name: database_version
        description: "The database version to use: SQLSERVER_2017_STANDARD, SQLSERVER_2017_ENTERPRISE, SQLSERVER_2017_EXPRESS, or SQLSERVER_2017_WEB"
        varType: string
        defaultValue: SQLSERVER_2017_STANDARD
      - name: db_charset
        description: The charset for the default database
        varType: string
        defaultValue: ""
      - name: db_collation
        description: "The collation for the default database. Example: 'en_US.UTF8'"
        varType: string
        defaultValue: ""
      - name: db_name
        description: The name of the default database to create
        varType: string
        defaultValue: default
      - name: delete_timeout
        description: The optional timeout that is applied to limit long database deletes.
        varType: string
        defaultValue: 30m
      - name: deletion_protection
        description: Used to block Terraform from deleting a SQL Instance.
        varType: bool
        defaultValue: true
      - name: deletion_protection_enabled
        description: Enables protection of an instance from accidental deletion protection across all surfaces (API, gcloud, Cloud Console and Terraform).
        varType: bool
        defaultValue: false
      - name: deny_maintenance_period
        description: The Deny Maintenance Period fields to prevent automatic maintenance from occurring during a 90-day time period. List accepts only one value. See [more details](https://cloud.google.com/sql/docs/sqlserver/maintenance)
        varType: |-
          list(object({
              end_date   = string
              start_date = string
              time       = string
            }))
        defaultValue: []
      - name: disk_autoresize
        description: Configuration to increase storage size.
        varType: bool
        defaultValue: true
      - name: disk_autoresize_limit
        description: The maximum size to which storage can be auto increased.
        varType: number
        defaultValue: 0
      - name: disk_size
        description: The disk size for the Cloud SQL instance.
        varType: number
        defaultValue: 10
      - name: disk_type
        description: The disk type for the Cloud SQL instance.
        varType: string
        defaultValue: PD_SSD
      - name: edition
        description: The edition of the instance, can be ENTERPRISE or ENTERPRISE_PLUS.
        varType: string
      - name: enable_default_db
        description: Enable or disable the creation of the default database
        varType: bool
        defaultValue: true
      - name: enable_default_user
        description: Enable or disable the creation of the default user
        varType: bool
        defaultValue: true
      - name: encryption_key_name
        description: The full path to the encryption key used for the CMEK disk encryption
        varType: string
      - name: follow_gae_application
        description: A Google App Engine application whose zone to remain in. Must be in the same region as this instance.
        varType: string
      - name: instance_type
        description: The type of the instance. The supported values are SQL_INSTANCE_TYPE_UNSPECIFIED, CLOUD_SQL_INSTANCE, ON_PREMISES_INSTANCE and READ_REPLICA_INSTANCE. Set to READ_REPLICA_INSTANCE when primary_instance_name is provided
        varType: string
        defaultValue: CLOUD_SQL_INSTANCE
      - name: ip_configuration
        description: The ip configuration for the Cloud SQL instances.
        varType: |-
          object({
              authorized_networks = optional(list(map(string)), [])
              ipv4_enabled        = optional(bool)
              private_network     = optional(string)
              require_ssl         = optional(bool)
              allocated_ip_range  = optional(string)
            })
        defaultValue:
          allocated_ip_range: null
          authorized_networks: []
          ipv4_enabled: true
          private_network: null
          require_ssl: null
      - name: maintenance_window_day
        description: The day of week (1-7) for the Cloud SQL maintenance.
        varType: number
        defaultValue: 1
      - name: maintenance_window_hour
        description: The hour of day (0-23) maintenance window for the Cloud SQL maintenance.
        varType: number
        defaultValue: 23
      - name: maintenance_window_update_track
        description: The update track of maintenance window for the Cloud SQL maintenance.Can be either `canary` or `stable`.
        varType: string
        defaultValue: canary
      - name: master_instance_name
        description: Name of the master instance if this is a failover replica. Required for creating failover replica instance. Not needed for master instance. When removed, next terraform apply will promote this failover failover replica instance as master instance
        varType: string
      - name: module_depends_on
        description: List of modules or resources this module depends on.
        varType: list(any)
        defaultValue: []
      - name: name
        description: The name of the Cloud SQL instance
        varType: string
        required: true
      - name: pricing_plan
        description: The pricing plan for the Cloud SQL instance.
        varType: string
        defaultValue: PER_USE
      - name: project_id
        description: The project ID to manage the Cloud SQL resources
        varType: string
        required: true
      - name: random_instance_name
        description: Sets random suffix at the end of the Cloud SQL resource name
        varType: bool
        defaultValue: false
      - name: region
        description: The region of the Cloud SQL resources
        varType: string
        defaultValue: us-central1
      - name: root_password
        description: MSSERVER password for the root user. If not set, a random one will be generated and available in the root_password output variable.
        varType: string
        defaultValue: ""
      - name: secondary_zone
        description: "The preferred zone for the read replica instance, it should be something like: `us-central1-a`, `us-east1-c`."
        varType: string
      - name: sql_server_audit_config
        description: SQL server audit config settings.
        varType: map(string)
        defaultValue: {}
      - name: tier
        description: The tier for the Cloud SQL instance.
        varType: string
        defaultValue: db-custom-2-3840
      - name: time_zone
        description: The time zone for Cloud SQL instance.
        varType: string
      - name: update_timeout
        description: The optional timeout that is applied to limit long database updates.
        varType: string
        defaultValue: 30m
      - name: user_labels
        description: The key/value labels for the Cloud SQL instances.
        varType: map(string)
        defaultValue: {}
      - name: user_name
        description: The name of the default user
        varType: string
        defaultValue: default
      - name: user_password
        description: The password for the default user. If not set, a random one will be generated and available in the generated_user_password output variable.
        varType: string
        defaultValue: ""
      - name: zone
        description: The zone for the Cloud SQL instance.
        varType: string
    outputs:
      - name: additional_users
        description: List of maps of additional users and passwords
      - name: generated_user_password
        description: The auto generated default user password if not input password was provided
      - name: instance_address
        description: The IPv4 addesses assigned for the master instance
      - name: instance_connection_name
        description: The connection name of the master instance to be used in connection strings
      - name: instance_first_ip_address
        description: The first IPv4 address of the addresses assigned.
      - name: instance_name
        description: The instance name for the master instance
      - name: instance_self_link
        description: The URI of the master instance
      - name: instance_server_ca_cert
        description: The CA certificate information used to connect to the SQL instance via SSL
      - name: instance_service_account_email_address
        description: The service account email address assigned to the master instance
      - name: primary
        description: The `google_sql_database_instance` resource representing the primary instance
      - name: private_address
        description: The private IP address assigned for the master instance
      - name: root_password
        description: MSSERVER password for the root user. If not set, a random one will be generated and available in the root_password output variable.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/cloudkms.admin
          - roles/cloudkms.cryptoKeyEncrypterDecrypter
          - roles/cloudscheduler.admin
          - roles/cloudsql.admin
          - roles/compute.admin
          - roles/compute.networkAdmin
          - roles/iam.serviceAccountAdmin
          - roles/iam.serviceAccountUser
          - roles/monitoring.editor
          - roles/resourcemanager.projectIamAdmin
          - roles/storage.admin
          - roles/workflows.admin
    services:
      - cloudkms.googleapis.com
      - cloudresourcemanager.googleapis.com
      - cloudscheduler.googleapis.com
      - compute.googleapis.com
      - iam.googleapis.com
      - monitoring.googleapis.com
      - servicenetworking.googleapis.com
      - serviceusage.googleapis.com
      - sqladmin.googleapis.com
      - workflows.googleapis.com
