apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-sql-db
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: GCP CloudSQL Restore
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-sql-db.git
      sourceType: git
      dir: /modules/restore
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: mssql-failover-replica
        location: examples/mssql-failover-replica
      - name: mssql-public
        location: examples/mssql-public
      - name: mysql-backup-create-service-account
        location: examples/mysql-backup-create-service-account
      - name: mysql-ha
        location: examples/mysql-ha
      - name: mysql-private
        location: examples/mysql-private
      - name: mysql-psc
        location: examples/mysql-psc
      - name: mysql-public
        location: examples/mysql-public
      - name: postgresql-backup-provided-service-account
        location: examples/postgresql-backup-provided-service-account
      - name: postgresql-ha
        location: examples/postgresql-ha
      - name: postgresql-psc
        location: examples/postgresql-psc
      - name: postgresql-public
        location: examples/postgresql-public
      - name: postgresql-public-iam
        location: examples/postgresql-public-iam
      - name: postgresql-with-cross-region-failover
        location: examples/postgresql-with-cross-region-failover
      - name: private_service_access
        location: examples/private_service_access
  interfaces:
    variables:
      - name: region
        description: The region to run the workflow
        varType: string
        defaultValue: us-central1
      - name: service_account
        description: The service account to use for running the workflow and triggering the workflow by Cloud Scheduler - If empty or null a service account will be created. If you have provided a service account you need to grant the Cloud SQL Admin and the Workflows Invoker role to that
        varType: string
      - name: project_id
        description: The project ID
        varType: string
        required: true
      - name: sql_instance
        description: The name of the SQL instance to backup
        varType: string
        required: true
      - name: import_databases
        description: The list of databases that should be imported - if is an empty set all databases will be imported
        varType: set(string)
        defaultValue: []
      - name: import_uri
        description: The bucket and path uri of GCS backup file for importing
        varType: string
        required: true
    outputs:
      - name: import_workflow_name
        description: The name for import workflow
      - name: region
        description: The region for running the scheduler and workflow
      - name: service_account
        description: The service account email running the scheduler and workflow
  requirements:
    roles:
      - level: Project
        roles:
          - roles/cloudsql.admin
          - roles/iam.serviceAccountUser
          - roles/logging.logWriter
    services:
      - serviceusage.googleapis.com
      - sqladmin.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.0, < 7"
